SELECT  J.AUTHOR_ID, J.AUTHOR_NAME, J.CATEGORY, 
        SUM(J.PRICE * S.SALES) AS TOTAL_SALES
  FROM  (
        SELECT  B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, B.PUBLISHED_DATE,
                A.AUTHOR_NAME
          FROM  BOOK B
          JOIN  AUTHOR A
            ON  B.AUTHOR_ID = A.AUTHOR_ID
        ) J
  JOIN  BOOK_SALES S
    ON  J.BOOK_ID = S.BOOK_ID
 WHERE  S.SALES_DATE LIKE '2022-01%'
 GROUP
    BY  J.AUTHOR_ID, J.AUTHOR_NAME, J.CATEGORY
 ORDER
    BY  AUTHOR_ID, CATEGORY DESC

