WITH AVAILABLE_CAR AS (
    -- 1. 세단/SUV이면서 11월에 대여 기록이 '전혀' 없는 차들만 선정
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
      AND CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
      )
),
DISCOUNT_PLAN AS (
    -- 2. 30일 이상 대여 시의 할인율만 미리 정리
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT C.CAR_ID, 
       C.CAR_TYPE, 
       ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) AS FEE
FROM AVAILABLE_CAR C
JOIN DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;