WITH RECURSIVE GENERATION_CTE AS (
    -- Base case: 최초 개체 (PARENT_ID IS NULL) → 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- Recursive case: 부모 세대 + 1
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATION_CTE g ON e.PARENT_ID = g.ID
)

SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM GENERATION_CTE
WHERE ID NOT IN (
    SELECT PARENT_ID 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL  -- NULL이 IN절에 포함되면 결과 이상해짐
)
GROUP BY GENERATION
ORDER BY GENERATION;