SELECT CASE
           WHEN (d.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) > 0
                AND (d.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE NAME = 'Python')) > 0
               THEN 'A'
           WHEN (d.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE NAME = 'C#')) > 0
               THEN 'B'
           WHEN (d.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) > 0
               THEN 'C'
       END AS GRADE,
       d.ID,
       d.EMAIL
FROM   DEVELOPERS d
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;